# Site settings
title: a gift for dora
description: a gift
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Congratulations
user_description: 恭喜玩家(198****2156)完成拼图，奖励粘粘怪一只！
email: zrh2126446@163.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
